clone_depth: 200

environment:
  global:
    MINGW: C:\Qt\Tools\mingw492_32
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32
    - QTDIR: C:\Qt\5.5\msvc2013_64

configuration: Release

install:
  - choco install -y nsis -version 2.49
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin

build_script:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%VERSION%
  - if defined APPVEYOR_REPO_TAG_NAME echo Building Tiled %VERSION%... (from %COMMITNOW%)
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
  - if not defined APPVEYOR_REPO_TAG_NAME set BUILD_INFO_VERSION=%COMMITNOW%
  - if not defined APPVEYOR_REPO_TAG_NAME echo Building Tiled daily %VERSION%... (from %COMMITNOW%)
  - qbs setup-toolchains --detect
  - qbs config profiles.i686-w64-mingw32.cpp.archiverPath ar.exe
  - qbs config profiles.i686-w64-mingw32.cpp.nmPath nm.exe
  - qbs config profiles.i686-w64-mingw32.cpp.objcopyPath objcopy.exe
  - qbs config profiles.i686-w64-mingw32.cpp.stripPath strip.exe
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - qbs install --all-products --install-root install-root release

after_build:
  - cd qt-release
  - cd dist*
  - move tiled-*-setup.exe %APPVEYOR_BUILD_FOLDER%

artifacts:
  - name: Installer
    path: 'tiled-*-setup.exe'

deploy:
  - provider: GitHub
    release: Tiled $(VERSION)
    auth_token:
      secure: 57ahePdHlJPeOX8/MqsIg5ho4x512wvAbwRA7TkXAOav/JTHvkTG5gf8k37/883r
    artifact: /.*\.exe/
    draft: true
    on:
        appveyor_repo_tag: true

  - provider: FTP
    protocol: sftp
    host: files.mapeditor.org
    username: bjorn
    password:
      secure: Hx5YfCOtpeBbftD4qnVCRLUGmMU9nogJTlSxq0xNbJQ=
    folder: public_html/files.mapeditor.org/public/daily
    on:
        branch: master
        appveyor_repo_tag: false

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/6e48d432e0e0dd1b2d22
