clone_depth: 200
version: '1.0.{build}'

environment:
  my_secret:
    secure: +3IhWT10lCSC4GE4gGfWt8WiZdIXuMUfaImgvQUullg=
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2013_64
      PUSH_RELEASE: true
      TILED_ITCH_CHANNEL: windows-64bit
    - QTDIR: C:\Qt\5.9\mingw53_32
      MINGW: C:\Qt\Tools\mingw530_32
      PUSH_RELEASE: true
      TILED_ITCH_CHANNEL: windows-32bit
    - QTDIR: C:\Qt\5.6\mingw49_32
      MINGW: C:\Qt\Tools\mingw492_32
      PUSH_RELEASE: false
      TILED_ITCH_CHANNEL: winxp-32bit

configuration: Release

install:
  - choco install -y qbs --version 1.9.1
  - nuget install secure-file -ExcludeVersion
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%
  - set TILED_SPARKLE=true
  - if defined APPVEYOR_REPO_TAG_NAME (set TILED_RELEASE=true) else (set TILED_SNAPSHOT=true)
  - if defined TILED_RELEASE set TILED_VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined TILED_RELEASE echo Building Tiled %TILED_VERSION%... (from %COMMITNOW%)
  - if defined TILED_SNAPSHOT set TILED_VERSION=%APPVEYOR_BUILD_VERSION%
  - if defined TILED_SNAPSHOT echo Building Tiled snapshot %TILED_VERSION%... (from %COMMITNOW%)
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - if defined TILED_RELEASE (set TILED_ITCH_VERSION=%TILED_VERSION%) else (set TILED_ITCH_VERSION=%VERSION_DATE%)
  - if defined TILED_SNAPSHOT (set TILED_ITCH_CHANNEL=%TILED_ITCH_CHANNEL%-snapshot)
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER if [%APPVEYOR_REPO_BRANCH%]==[snapshot] set PUSH_TO_ITCH=true
  - qbs build --all-products release projects.Tiled.windowsInstaller:true
  - qbs build --all-products itch qbs.buildVariant:release projects.Tiled.sparkleEnabled:false projects.Tiled.version:%TILED_ITCH_VERSION%
  - cd util\java
  - mvn --version
  - mvn clean install
  - cd ..\..

after_build:
  - cd release
  - cd installer*
  - move tiled-*.msi %APPVEYOR_BUILD_FOLDER%
  - if defined TILED_SNAPSHOT move appcast-win*-snapshots.xml %APPVEYOR_BUILD_FOLDER%
  - cd ..\..
  - cd itch
  - cd archive*
  - move tiled-*.7z %APPVEYOR_BUILD_FOLDER%
  - cd ..\..
  - if defined PUSH_TO_ITCH dist\win\push-to-itch.bat

artifacts:
  - name: Installer
    path: 'tiled-*.msi'
  - name: Archive
    path: 'tiled-*.7z'
  - name: AppCast
    path: 'appcast-win*-snapshots.xml'

cache:
  - C:\Users\appveyor\.m2

deploy:
  - provider: GitHub
    release: Tiled $(TILED_VERSION)
    auth_token:
      secure: 57ahePdHlJPeOX8/MqsIg5ho4x512wvAbwRA7TkXAOav/JTHvkTG5gf8k37/883r
    artifact: /.*\.msi/
    draft: true
    on:
        appveyor_repo_tag: true
        push_release: true

  - provider: FTP
    protocol: sftp
    host: update.mapeditor.org
    username: bjorn
    password:
      secure: Hx5YfCOtpeBbftD4qnVCRLUGmMU9nogJTlSxq0xNbJQ=
    folder: sparkle/snapshots-win
    artifact: /.*\.(msi|7z)/
    on:
        branch: snapshot
        appveyor_repo_tag: false
        push_release: true

  - provider: FTP
    protocol: sftp
    host: update.mapeditor.org
    username: bjorn
    password:
      secure: Hx5YfCOtpeBbftD4qnVCRLUGmMU9nogJTlSxq0xNbJQ=
    folder: sparkle
    artifact: /appcast-win.*-snapshots\.xml/
    on:
        branch: snapshot
        appveyor_repo_tag: false
        push_release: true

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/6e48d432e0e0dd1b2d22
