site_name: Tiled Documentation
repo_url: https://github.com/bjorn/tiled
theme: cerulean
google_analytics: ['UA-380618-1', 'mapeditor.org']
pages:
- Home: index.md
- Manual:
    - Contents: manual/index.md
    - Using the Terrain Tool: manual/using-the-terrain-tool.md
    - Using Commands: manual/using-commands.md
- Reference:
    - TMX Map Format: reference/tmx-map-format.md
    - TMX Changelog: reference/tmx-changelog.md
    - Libraries and Frameworks: reference/support-for-tmx-maps.md
